name: Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
      
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Use Exiftool
        uses: woss/exiftool-action@v12.87

      - uses: mfinelli/setup-imagemagick@v5

      - name: build
        run: /bin/bash process.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          error_count: 3